from variables import *

SEVERE_RENT_ALL_COUNTIES = BASE_URL \
    + GET + GROSS_RENT_PERCENT_INCOME_50_PLUS \
    + FOR + COUNTY + "*" \
    + IN + STATE + OREGON

 
SUM_SEVERE_RENT_BURDEN = BASE_URL \
    + GET + GROSS_RENT_PERCENT_INCOME_30_34 + COMMA + GROSS_RENT_PERCENT_INCOME_35_39 + COMMA + GROSS_RENT_PERCENT_INCOME_40_49\
    + FOR + COUNTY + "*" \
    + IN + STATE + OREGON

TOTAL_POPULATION_BURDENED_OREGON = BASE_URL \
    + GET + TOTAL_POPULATION_BURDENED \
    + FOR + COUNTY + "*" \
    + IN + STATE + OREGON
